spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: java
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8001
  servlet:
    context-path: /banker-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic